# Generated by Django 4.2.11 on 2024-03-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_servings_alter_recipe_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
